// FlClashTier M1: thin C++ implementation of the C ABI wrapper.
// Includes ZeroTierOne.h (C++ header) and links against libzerotiercore.a.
//
// M1 adds the frame plane on top of the M1-3 wire plane:
//   - virtualNetworkFrameFunction buffers incoming frames in a C-side queue
//     (Go pulls via flclashtier_zt_frame_pull).
//   - flclashtier_zt_send_frame wraps ZT_Node_processVirtualNetworkFrame.
//   - snapshot now carries status/mac/mtu/assigned addresses.
//   - a node mutex serializes ALL ZT_Node_* entry points (ZeroTier Node is
//     not thread-safe; official Android drives it from a single thread).
#include "wrapper.h"
#include "ZeroTierOne.h"
#include "planet_data.h"   // official ZeroTier planet (570 bytes), generated by xxd -i
#include <cstring>
#include <cstdio>
#include <chrono>
#include <mutex>
#include <arpa/inet.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <unistd.h>
#include <errno.h>

// ---------------------------------------------------------------------------
// Node-wide mutex: ZeroTier Node is NOT thread-safe. Every ZT_Node_* entry
// point below serializes through this mutex. The wire send callback and the
// config/frame callbacks are invoked synchronously INSIDE a ZT_Node_* call,
// so they must NOT take this mutex (deadlock). They use their own mutexes.
// ---------------------------------------------------------------------------
static std::mutex g_nodeMutex;

// ---------------------------------------------------------------------------
// State persistence
// ---------------------------------------------------------------------------
static char g_identityPath[512] = "";

static void statePutFunction(ZT_Node* node, void* uptr, void* tptr,
                             enum ZT_StateObjectType type, const uint64_t id[2],
                             const void* data, int len) {
  (void)node; (void)uptr; (void)tptr; (void)type; (void)id;
  if (type == ZT_STATE_OBJECT_IDENTITY_SECRET && g_identityPath[0] && data && len > 0) {
    FILE* f = fopen(g_identityPath, "wb");
    if (f) {
      fwrite(data, 1, (size_t)len, f);
      fclose(f);
      chmod(g_identityPath, 0600);
    }
  }
  // PLANET / PEER / NETWORK_CONFIG persistence is optional for M1.
}

static int stateGetFunction(ZT_Node* node, void* uptr, void* tptr,
                            enum ZT_StateObjectType type, const uint64_t id[2],
                            void* data, unsigned int maxlen) {
  (void)node; (void)uptr; (void)tptr; (void)id;
  if (type == ZT_STATE_OBJECT_PLANET) {
    unsigned int n = (unsigned int)_var_lib_zerotier_one_planet_len;
    if (data == NULL) return (int)n;
    if (maxlen < n) return -1;
    memcpy(data, _var_lib_zerotier_one_planet, n);
    return (int)n;
  }
  if (type == ZT_STATE_OBJECT_IDENTITY_SECRET && g_identityPath[0]) {
    FILE* f = fopen(g_identityPath, "rb");
    if (f) {
      fseek(f, 0, SEEK_END);
      long n = ftell(f);
      fseek(f, 0, SEEK_SET);
      if (n > 0 && data != NULL && (unsigned long)n <= maxlen) {
        size_t rd = fread(data, 1, (size_t)n, f);
        fclose(f);
        if (rd == (size_t)n) return (int)n;
      } else {
        fclose(f);
        return -1;
      }
    }
    return -1;  // no identity yet -> core generates one, statePut persists it
  }
  return -1;  // not found
}

// ---------------------------------------------------------------------------
// Wire send: ZeroTier core never creates sockets; it calls this with an
// opaque localSocket (usually -1 in single-socket mode) + remote address +
// payload. data is the encrypted VL1 packet = pure UDP payload.
// NOTE: called from inside ZT_Node_* calls (g_nodeMutex already held).
// ---------------------------------------------------------------------------
static int g_sockFd = -1;
static ZT_Node* s_node = NULL;

static int wirePacketSendFunction(ZT_Node* node, void* uptr, void* tptr,
                                  int64_t now, const struct sockaddr_storage* remoteAddr,
                                  const void* data, unsigned int len, unsigned int ttl) {
  (void)node; (void)uptr; (void)tptr; (void)now; (void)ttl;
  if (g_sockFd < 0) return -1;
  ssize_t n = sendto(g_sockFd, data, len, 0,
                     reinterpret_cast<const struct sockaddr*>(remoteAddr),
                     sizeof(struct sockaddr_storage));
  return (n == static_cast<ssize_t>(len)) ? 0 : -1;
}

// ---------------------------------------------------------------------------
// Frame plane: incoming virtual frames are buffered in a C-side ring queue.
// ---------------------------------------------------------------------------
static std::mutex g_frameMutex;
static flclashtier_zt_frame g_frameQueue[FLCLASHTIER_ZT_FRAME_QUEUE];
static int g_frameHead = 0;   // index of oldest
static int g_frameCount = 0;
static uint64_t g_frameDropped = 0;

static void virtualNetworkFrameFunction(ZT_Node* node, void* uptr, void* tptr,
                                        uint64_t nwid, void** nuptr, uint64_t sourceMac,
                                        uint64_t destMac, unsigned int etherType,
                                        unsigned int vlanId, const void* frameData,
                                        unsigned int frameLength) {
  (void)node; (void)uptr; (void)tptr; (void)nuptr;
  std::lock_guard<std::mutex> lock(g_frameMutex);
  if (g_frameCount >= FLCLASHTIER_ZT_FRAME_QUEUE) {
    // queue full: drop oldest to keep the newest
    g_frameHead = (g_frameHead + 1) % FLCLASHTIER_ZT_FRAME_QUEUE;
    g_frameCount--;
    g_frameDropped++;
  }
  flclashtier_zt_frame* f = &g_frameQueue[(g_frameHead + g_frameCount) % FLCLASHTIER_ZT_FRAME_QUEUE];
  f->nwid = nwid;
  f->srcMac = sourceMac;
  f->dstMac = destMac;
  f->etherType = (uint16_t)etherType;
  f->vlanId = (uint16_t)vlanId;
  uint32_t n = (frameLength > FLCLASHTIER_ZT_FRAME_MAX) ? FLCLASHTIER_ZT_FRAME_MAX : frameLength;
  f->len = n;
  if (frameData && n > 0) memcpy(f->data, frameData, n);
  g_frameCount++;
}

// ---------------------------------------------------------------------------
// Config snapshot (thread-safe; C-side deep copy, Go pulls)
// ---------------------------------------------------------------------------
static std::mutex g_snapMutex;
static flclashtier_zt_snapshot g_snapshot;
static uint64_t g_generation = 0;

static uint8_t sockaddrFamily(const struct sockaddr_storage* addr) {
  if (addr->ss_family == AF_INET) return 4;
  if (addr->ss_family == AF_INET6) return 6;
  return 0;
}

static uint8_t sockaddrPrefixLen(const struct sockaddr_storage* addr) {
  if (addr->ss_family == AF_INET) {
    const struct sockaddr_in* v4 = reinterpret_cast<const struct sockaddr_in*>(addr);
    return static_cast<uint8_t>(ntohs(v4->sin_port));
  } else if (addr->ss_family == AF_INET6) {
    const struct sockaddr_in6* v6 = reinterpret_cast<const struct sockaddr_in6*>(addr);
    return static_cast<uint8_t>(ntohs(v6->sin6_port));
  }
  return 0;
}

static void copySockaddr(const struct sockaddr_storage* addr, uint8_t* out) {
  if (addr->ss_family == AF_INET) {
    const struct sockaddr_in* v4 = reinterpret_cast<const struct sockaddr_in*>(addr);
    memcpy(out, &v4->sin_addr, 4);
  } else if (addr->ss_family == AF_INET6) {
    const struct sockaddr_in6* v6 = reinterpret_cast<const struct sockaddr_in6*>(addr);
    memcpy(out, &v6->sin6_addr, 16);
  }
}

static void updateSnapshotLocked(uint64_t nwid,
                                 enum ZT_VirtualNetworkConfigOperation op,
                                 const ZT_VirtualNetworkConfig* config) {
  memset(&g_snapshot, 0, sizeof(g_snapshot));
  g_snapshot.nwid = nwid;
  g_snapshot.operation = static_cast<int>(op);
  if (config) {
    g_snapshot.status = static_cast<int>(config->status);
    g_snapshot.netconfRevision = config->netconfRevision;
    g_snapshot.mac = config->mac;
    g_snapshot.mtu = config->mtu;
    unsigned int na = config->assignedAddressCount;
    if (na > FLCLASHTIER_ZT_MAX_ASSIGNED) na = FLCLASHTIER_ZT_MAX_ASSIGNED;
    g_snapshot.assignedCount = na;
    for (unsigned int i = 0; i < na; ++i) {
      flclashtier_zt_assigned* dst = &g_snapshot.assigned[i];
      const struct sockaddr_storage& src = config->assignedAddresses[i];
      memset(dst, 0, sizeof(*dst));
      dst->family = sockaddrFamily(&src);
      dst->prefixLen = sockaddrPrefixLen(&src);
      copySockaddr(&src, dst->addr);
    }
    unsigned int rc = config->routeCount;
    if (rc > FLCLASHTIER_ZT_MAX_ROUTES) rc = FLCLASHTIER_ZT_MAX_ROUTES;
    g_snapshot.routeCount = rc;
    for (unsigned int i = 0; i < rc; ++i) {
      flclashtier_zt_route* dst = &g_snapshot.routes[i];
      const ZT_VirtualNetworkRoute& src = config->routes[i];
      memset(dst, 0, sizeof(*dst));
      dst->family = sockaddrFamily(&src.target);
      dst->prefixLen = sockaddrPrefixLen(&src.target);
      copySockaddr(&src.target, dst->target);
      copySockaddr(&src.via, dst->via);
      dst->flags = src.flags;
      dst->metric = src.metric;
    }
  }
  ++g_generation;
}

static int virtualNetworkConfigFunction(ZT_Node* node, void* uptr, void* tptr,
                                        uint64_t nwid, void** nuptr,
                                        enum ZT_VirtualNetworkConfigOperation op,
                                        const ZT_VirtualNetworkConfig* config) {
  (void)node; (void)uptr; (void)tptr; (void)nuptr;
  std::lock_guard<std::mutex> lock(g_snapMutex);
  updateSnapshotLocked(nwid, op, config);
  return 0;
}

static void eventCallback(ZT_Node* node, void* uptr, void* tptr,
                          enum ZT_Event event, const void* metaData) {
  (void)node; (void)uptr; (void)tptr; (void)event; (void)metaData;
  // Lifecycle events are visible through the snapshot (UP/CONFIG_UPDATE/DOWN).
}

// ---------------------------------------------------------------------------
// C ABI implementation
// ---------------------------------------------------------------------------

uint64_t flclashtier_zt_snapshot_export(flclashtier_zt_snapshot* out) {
  if (!out) return 0;
  std::lock_guard<std::mutex> lock(g_snapMutex);
  memcpy(out, &g_snapshot, sizeof(g_snapshot));
  return g_generation;
}

void flclashtier_zt_set_socket_fd(int fd) {
  std::lock_guard<std::mutex> lock(g_nodeMutex);
  g_sockFd = fd;
}

int flclashtier_zt_get_socket_fd(void) {
  std::lock_guard<std::mutex> lock(g_nodeMutex);
  return g_sockFd;
}

int flclashtier_zt_process_wire_packet(const struct sockaddr_storage* remoteAddr,
                                       const void* data, unsigned int len,
                                       int64_t now, int64_t* nextDeadline) {
  volatile int64_t deadline = 0;
  std::lock_guard<std::mutex> lock(g_nodeMutex);
  if (!s_node) return -1;
  enum ZT_ResultCode rc = ZT_Node_processWirePacket(s_node, NULL, now, -1,
      remoteAddr, data, len, &deadline);
  if (nextDeadline) *nextDeadline = static_cast<int64_t>(deadline);
  return static_cast<int>(rc);
}

int flclashtier_zt_process_background_tasks(int64_t now, int64_t* nextDeadline) {
  volatile int64_t deadline = 0;
  std::lock_guard<std::mutex> lock(g_nodeMutex);
  if (!s_node) return -1;
  enum ZT_ResultCode rc = ZT_Node_processBackgroundTasks(s_node, NULL, now, &deadline);
  if (nextDeadline) *nextDeadline = static_cast<int64_t>(deadline);
  return static_cast<int>(rc);
}

int flclashtier_zt_join(uint64_t nwid) {
  std::lock_guard<std::mutex> lock(g_nodeMutex);
  if (!s_node) return -1;
  return static_cast<int>(ZT_Node_join(s_node, nwid, NULL, NULL));
}

int flclashtier_zt_leave(uint64_t nwid) {
  std::lock_guard<std::mutex> lock(g_nodeMutex);
  if (!s_node) return -1;
  void* nuptr = NULL;
  return static_cast<int>(ZT_Node_leave(s_node, nwid, &nuptr, NULL));
}

int flclashtier_zt_frame_pull(flclashtier_zt_frame* out) {
  if (!out) return 0;
  std::lock_guard<std::mutex> lock(g_frameMutex);
  if (g_frameCount <= 0) return 0;
  memcpy(out, &g_frameQueue[g_frameHead], sizeof(flclashtier_zt_frame));
  g_frameHead = (g_frameHead + 1) % FLCLASHTIER_ZT_FRAME_QUEUE;
  g_frameCount--;
  return 1;
}

int flclashtier_zt_frame_pending(void) {
  std::lock_guard<std::mutex> lock(g_frameMutex);
  return g_frameCount;
}

uint64_t flclashtier_zt_frame_dropped(void) {
  std::lock_guard<std::mutex> lock(g_frameMutex);
  return g_frameDropped;
}

int flclashtier_zt_send_frame(uint64_t nwid, uint64_t srcMac, uint64_t dstMac,
                              uint16_t etherType, uint16_t vlanId,
                              const void* data, unsigned int len,
                              int64_t* nextDeadline) {
  volatile int64_t deadline = 0;
  std::lock_guard<std::mutex> lock(g_nodeMutex);
  if (!s_node) return -1;
  int64_t now = std::chrono::duration_cast<std::chrono::milliseconds>(
      std::chrono::system_clock::now().time_since_epoch()).count();
  enum ZT_ResultCode rc = ZT_Node_processVirtualNetworkFrame(s_node, NULL,
      now, nwid, srcMac, dstMac, etherType, vlanId, data, len, &deadline);
  if (nextDeadline) *nextDeadline = static_cast<int64_t>(deadline);
  return static_cast<int>(rc);
}

int flclashtier_zt_multicast_subscribe(uint64_t nwid, uint64_t multicastGroup, uint32_t adi) {
  std::lock_guard<std::mutex> lock(g_nodeMutex);
  if (!s_node) return -1;
  return static_cast<int>(ZT_Node_multicastSubscribe(s_node, NULL, nwid, multicastGroup, adi));
}

int flclashtier_zt_multicast_unsubscribe(uint64_t nwid, uint64_t multicastGroup, uint32_t adi) {
  std::lock_guard<std::mutex> lock(g_nodeMutex);
  if (!s_node) return -1;
  return static_cast<int>(ZT_Node_multicastUnsubscribe(s_node, nwid, multicastGroup, adi));
}

flclashtier_zt_node* flclashtier_zt_node_new(void) {
  ZT_Node_Callbacks cb;
  memset(&cb, 0, sizeof(cb));
  cb.version = 0;
  cb.statePutFunction = statePutFunction;
  cb.stateGetFunction = stateGetFunction;
  cb.wirePacketSendFunction = wirePacketSendFunction;
  cb.virtualNetworkFrameFunction = virtualNetworkFrameFunction;
  cb.virtualNetworkConfigFunction = virtualNetworkConfigFunction;
  cb.eventCallback = eventCallback;

  std::lock_guard<std::mutex> lock(g_nodeMutex);
  if (s_node) return reinterpret_cast<flclashtier_zt_node*>(s_node);  // already created
  ZT_Node* node = NULL;
  enum ZT_ResultCode rc = ZT_Node_new(&node, NULL, NULL, &cb, 0);
  if (rc != ZT_RESULT_OK || node == NULL) {
    return NULL;
  }
  s_node = node;
  return reinterpret_cast<flclashtier_zt_node*>(node);
}

void flclashtier_zt_node_delete(flclashtier_zt_node* node) {
  std::lock_guard<std::mutex> lock(g_nodeMutex);
  if (node == NULL) return;
  if (s_node == reinterpret_cast<ZT_Node*>(node)) {
    s_node = NULL;
  }
  ZT_Node_delete(reinterpret_cast<ZT_Node*>(node));
}

uint64_t flclashtier_zt_node_address(void) {
  std::lock_guard<std::mutex> lock(g_nodeMutex);
  if (!s_node) return 0;
  return ZT_Node_address(s_node);
}

void flclashtier_zt_set_identity_path(const char* path) {
  if (path == NULL) { g_identityPath[0] = '\0'; return; }
  strncpy(g_identityPath, path, sizeof(g_identityPath) - 1);
  g_identityPath[sizeof(g_identityPath) - 1] = '\0';
}

const char* flclashtier_zt_version(void) {
  int major = 0, minor = 0, revision = 0;
  ZT_version(&major, &minor, &revision);
  static char buf[32];
  snprintf(buf, sizeof(buf), "%d.%d.%d", major, minor, revision);
  return buf;
}
